### ISSUE TITLE
 same issuer/serial as an existing cert

### ISSUE THREAD

**Issue by slmagus** [rabbitmq/tls-gen#35]
Steps to reproduce:
  1. use tls-gen to generate a server certificate for server alpha on alpha.
  2. use tls-gen to generate another server certificate for server beta on beta.
  3. You should now have two server alpha and beta running with self signed certs
  4. using something like FF to connect to your endpoint on alpha. Assuming a self-signed cert install the ca expection.
  5. Connection to alpha is successful
  6. Repeat step 4,5. Attempting to connect to beta results in the  same issuer/serial as an existing cert
  
Per RFC https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.2
Serial numbers with an issuer must be unique, and there no more then 20 bytes(octets) thus between range between one and n^(20*8)

Workaround:
Remove the exception for alpha and reinstall exception for beta.

Error message details:
An error occurred during a connection to beta. You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

[root@9dfe45c9f207 result]# openssl x509 -text -noout -in server_alpha_certificate.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = TLSGenSelfSignedtRootCA, L = $$$$

As we don't yet support multiple client certificate generations fully. I think the best current plan would be to randomize the serial number upon generation. Hopefully we avoid any collisions that way.

**Comment by michaelklishin** [comment]
Changing [this line](https://github.com/michaelklishin/tls-gen/blob/b8517957f68e31ace1301dffbc975d8a879f78ac/tls_gen/gen.py#L98) to use a sufficiently unique value should do it.
