### ISSUE TITLE
Rename default branch to main?

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/tls-gen#44]
We have done this (switch to a more modern and hopefully non-offensive branch name) in almost all smaller RabbitMQ-related projects. Should we branch `main` off of `master`, make it the default branch and continue there? I doubt anyone
checks out `master` specifically but we can delay its removal by a few months (at the risk of some confusion).

This can be done after all PRs under active development are merged.

@lukebakken

**Comment by lukebakken** [comment]
We can directly do the rename here. I'll get it once I'm done with #42

**Comment by lukebakken** [comment]
#42 is merged and `master` renamed to `main`.
